# -*- coding: utf-8 -*-
#
# Copyright 2018-26 Zeroincombenze srls <https://www.zeroincombenze.it>
#
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).
#
import logging

from odoo import api, fields, models

from odoo.addons.l10n_it_ade.bindings import fatturapa_v_1_2

_logger = logging.getLogger(__name__)


class FatturaPAAttachmentOut(models.Model):
    """Sale e-invoice files, either issued by Odoo or imported from outside.

    l10n_it_einvoice_out fills this model when Odoo generates the xml file, so
    every datum is read back from the linked invoices. A file imported from an
    external source has no linked invoice yet: data are then read from the xml
    itself, the same way l10n_it_einvoice_in does for purchase files.

    None of the fields added here is stored. Installing a stored computed
    field makes the ORM recompute it for every existing row in one
    transaction, which on a real database means parsing thousands of xml
    files at once - and failing outright on any file that cannot be read,
    such as in a database restored without its filestore.
    """

    _inherit = "fatturapa.attachment.out"

    imported = fields.Boolean(
        "Imported File",
        readonly=True,
        copy=False,
        help="Set when the xml file was loaded from outside, rather than "
        "generated by this system.",
    )
    registered = fields.Boolean(
        "Registered",
        compute="_compute_registered",
        search="_search_registered",
        help="The invoices of this file are registered in Odoo.",
    )
    invoices_count = fields.Integer(
        "Invoices Number",
        compute="_compute_invoices_count",
        help="Number of invoice bodies contained in the xml file.",
    )

    @api.model
    def create(self, vals):
        """A file not generated here was already sent to SdI by whoever made it.

        Only the export wizard of l10n_it_einvoice_out creates a file that is
        still to be sent, and it says so through the context. Every other file
        is loaded from outside, so it is marked as already sent: left in the
        "ready" state, the send_all_xml_invoices cron of
        l10n_it_einvoice_send2sdi would send it to SdI a second time, as soon
        as the hour after the upload. An operator who really wants to send one
        can still use the "Reset to ready" button.
        """
        if not self.env.context.get("einvoice_export"):
            vals = dict(vals)
            vals.setdefault("imported", True)
            # state belongs to l10n_it_einvoice_send2sdi, an optional dependency
            if "state" in self._fields:
                vals.setdefault("state", "sent")
        return super(FatturaPAAttachmentOut, self).create(vals)

    def get_normalized_xml_string(self):
        """Xml string cleaned up of the quirks the pyxb bindings reject.

        Kept apart from get_xml_string() so that the export flow, which reads
        back the file it just wrote, is left untouched.
        """
        if not self.ir_attachment_id:
            return False
        return self.ir_attachment_id.normalize_einvoice_xml(
            self.ir_attachment_id.get_xml_string()
        )

    @api.multi
    def get_invoice_obj(self):
        """Parsed xml file, or False when it cannot be read.

        The file of an attachment may be missing or corrupted; callers here
        display a record rather than import it, so they get False instead of
        an exception.
        """
        self.ensure_one()
        try:
            xml_string = self.get_normalized_xml_string()
            if xml_string:
                return fatturapa_v_1_2.CreateFromDocument(xml_string)
        except BaseException as e:
            _logger.warning(
                "Unreadable e-invoice file in attachment id %s: %s" % (self.id, e)
            )
        return False

    @api.multi
    @api.depends("out_invoice_ids")
    def _compute_registered(self):
        """No xml parsing: a file is registered once it has its invoices."""
        for att in self:
            att.registered = bool(att.out_invoice_ids)

    def _search_registered(self, operator, value):
        if operator not in ("=", "!="):
            raise ValueError("Unsupported operator %s" % operator)
        registered = bool(value) if operator == "=" else not value
        domain = [("out_invoice_ids", "!=", False)]
        if not registered:
            domain = [("out_invoice_ids", "=", False)]
        return domain

    @api.multi
    @api.depends("ir_attachment_id.datas", "out_invoice_ids")
    def _compute_invoices_count(self):
        for att in self:
            if att.out_invoice_ids:
                # Generated by this system: no need to read the file back
                att.invoices_count = len(att.out_invoice_ids)
                continue
            inv_xml = att.get_invoice_obj()
            att.invoices_count = len(inv_xml.FatturaElettronicaBody) if inv_xml else 0

    @api.multi
    @api.depends("ir_attachment_id.datas", "out_invoice_ids")
    def _compute_xml_data(self):
        """Fill the export fields of a file that has no invoices yet.

        super() reads them from the linked invoices, which is right for a file
        this system generated, and leaves an imported one empty: those are
        read from the xml instead.
        """
        linked = self.filtered(lambda att: att.out_invoice_ids)
        if linked:
            super(FatturaPAAttachmentOut, linked)._compute_xml_data()
        partner_model = self.env["res.partner"]
        for att in self - linked:
            att.invoices_total = 0.0
            att.invoices_number = ""
            inv_xml = att.get_invoice_obj()
            if not inv_xml:
                continue
            att.invoice_partner_id = partner_model.search_partner_from_xml(
                inv_xml.FatturaElettronicaHeader.CessionarioCommittente
            )
            invoices_total = 0.0
            invoices_number = ""
            for invoice_body in inv_xml.FatturaElettronicaBody:
                header = invoice_body.DatiGenerali.DatiGeneraliDocumento
                invoices_total += float(header.ImportoTotaleDocumento or 0)
                invoices_number += " %s" % header.Numero
                if not att.date_invoice0:
                    att.date_invoice0 = header.Data
            att.invoices_total = invoices_total
            att.invoices_number = invoices_number.strip()
