{
    "name": "Account Invoice - Tax round",
    "version": "12.0.0.1.1",
    "category": "Accounting & Finance",
    "summary": "Round taxes to comply italian laws",
    "author": "SHS-AV s.r.l.",
    "website": "https://www.zeroincombenze.it/crm",
    "development_status": "Beta",
    "license": "LGPL-3",
    "depends": ["account"],
    # "version_depends": ["account==10.0.1.1.2"],
    "maintainer": "Antonio M. Vigliotti <antoniomaria.vigliotti@gmail.com>",
    "installable": True,
    # "pre_init_hook": "check_4_depending",
}
